# Generated by Django 4.2.4 on 2023-08-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Fresh Flowers', (('Floral Bouquets', 'FLORAL BOUQUETS'), ('Floral Baskets', 'FLORAL BASKETS'), ('Floral Boxes', 'FLORAL BOXES'), ('Flowers In a Vase', 'FLOWERS IN A VASE'))), ('Floral Jewelry', (('Gajras And Garlands', 'GAJRAS & GARLANDS'), ('Plants', 'PLANTS')))], max_length=20, verbose_name='type of category'),
        ),
    ]
