# Generated by Django 4.2.4 on 2023-08-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0006_alter_category_options_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-title'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-title'], 'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
    ]
