# Generated by Django 4.2.4 on 2023-08-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_handler', '0002_cart_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.IntegerField(),
        ),
    ]
